name: Building documentation and deploying on gh-pages
on:
    schedule:
        - cron: '0 0 * * 0'
    push: 
        branches:
            - main

jobs:
    run_tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code 🛎️
              uses: actions/checkout@v2
              with:
                persist-credentials: false

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
                cache: "pip"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Install package
              shell: bash -l {0}
              run: |
                python -m pip list
                make install

            - name: Build the documentation
              shell: bash -l {0}
              run: |
                pushd doc
                make html
                touch _build/html/.nojekyll

            - name: Deploying article on github pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: doc/_build/html
                CLEAN: true

